name: ci main

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      version:
        type: string
        description: Release version
        required: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    env:
      TestFolder: tests
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    if: github.actor == 'peara'
    needs: [test,lint]
    runs-on: [self-hosted, aura]
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variable
        run: |
          SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
          echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/twilight-backend:${{ inputs.version }}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
          echo REPO_MANIFEST_NAME=gitops-prod >> $GITHUB_ENV
          echo REPO_MANIFEST_URL=github.com/aura-nw/gitops-prod.git >> $GITHUB_ENV
          echo REPO_MANIFEST_BRANCH=main >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_MAIN=./clusters/k8s-xstaxy/twilight >> $GITHUB_ENV
          echo REPO_MANIFEST_TAG_IMAGE=image_twilight_backend >> $GITHUB_ENV
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Build the Docker image and push it to the registry
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod 777 -R ./ci
          ./ci/build.sh
      - name: Update manifest
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          ./ci/updateManifest.sh
