name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [pull_request]

env:
  TEST_FOLDER: ${{ github.base_ref == 'main' && 'tests' || 'tests/services' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "test folder $TEST_FOLDER"
      - run: echo "GITHUB_BASE_REF $GITHUB_BASE_REF"
      - run: echo "GITHUB_REF $GITHUB_REF"
      - run: echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF"
    
